[package]
name = "channellib"
version = "0.2.2"
edition = "2024"
description = "tools for enriching communication between threads"
readme = "README.md"
repository = "https://github.com/ktausch/channellib"
license = "MIT"
keywords = ["channel", "threads", "communication", "sender", "receiver"]
categories = ["concurrency"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"
